version: '3'

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-12-12T19-27-27Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
    environment:
      - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    networks:
      - network-toko-indonesia
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    networks:
      - network-toko-indonesia
    environment:
      - OTEL_USERNAME=username
      - OTEL_PASSWORD=password
  
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - toko-indonesia-data1-1:/data1
      - toko-indonesia-data1-2:/data2
    networks:
      - network-toko-indonesia

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - toko-indonesia-data2-1:/data1
      - toko-indonesia-data2-2:/data2
    networks:
      - network-toko-indonesia

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - toko-indonesia-data3-1:/data1
      - toko-indonesia-data3-2:/data2
    networks:
      - network-toko-indonesia

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - toko-indonesia-data4-1:/data1
      - toko-indonesia-data4-2:/data2
    networks:
      - network-toko-indonesia

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./config/minio-nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      - network-toko-indonesia

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: pas12345
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - network-toko-indonesia
  
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass pas12345
    volumes: 
      - ./redis-data:/data
    networks:
      - network-toko-indonesia
  
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8200'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config/vault:/vault-config
      - toko-indonesia-vault-volume:/data
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: /bin/sh /vault-config/workflow-vault.sh
    networks:
      - network-toko-indonesia

networks:
  network-toko-indonesia:

volumes:
  toko-indonesia-data1-1:
  toko-indonesia-data1-2:
  toko-indonesia-data2-1:
  toko-indonesia-data2-2:
  toko-indonesia-data3-1:
  toko-indonesia-data3-2:
  toko-indonesia-data4-1:
  toko-indonesia-data4-2:
  toko-indonesia-vault-volume: