receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: basicauth/server

processors:
  batch:

exporters:
  zipkin:
    endpoint: http://zipkin-all-in-one:9411/api/v2/spans

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
  basicauth/server:
    htpasswd:
      inline: |
        ${env:OTEL_USERNAME}:${env:OTEL_PASSWORD}

service:
  extensions: [health_check, pprof, zpages, basicauth/server]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]